### ISSUE TITLE
discuon for al things timedragon

### ISSUE THREAD

**Issue by CluckCluckChicken** [Timed-kitty-cat/Timed-kitty-cat#61]
hi welcom to timecat discor oficcal github thx bai
![image](https://user-images.githubusercontent.com/46281840/126082109-c5729434-dbc8-416b-a873-dc10c59e237a.png)

**Comment by Timed-kitty-cat** [comment]
I don't have Discord

**Comment by CluckCluckChicken** [comment]
> I don't have Discord

JaredYoshi#0001 does tho and seems to be breaking tos

**Comment by CluckCluckChicken** [comment]
he is naughty though i bet you would never do such a thing

**Comment by Timed-kitty-cat** [comment]
> he is naughty

Not true. @JaredYoshi show this guy who's boss!

**Comment by Timed-kitty-cat** [comment]
Summoning in the mighty Yoshi lord, Jared!

**Comment by Timed-kitty-cat** [comment]
> seems to be breaking tos

TOS say nothing about having Discord

**Comment by CluckCluckChicken** [comment]
> > seems to be breaking tos
> 
> TOS say nothing about having Discord

discord tos say you have to be over 13 😱😱😳😳😂😂😅😅



> > he is naughty
> 
> Not true. @JaredYoshi show this guy who's boss!

ok

**Comment by Timed-kitty-cat** [comment]
> discord tos say you have to be over 13

No. They say you must be exactly 13.
